import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { LinearGradient } from "expo-linear-gradient";
import * as Print from "expo-print";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import * as Sharing from "expo-sharing";
import React from "react";
import { ActivityIndicator, ScrollView, StyleSheet, View } from "react-native";
import {
  Button,
  Chip,
  Divider,
  Surface,
  Text,
  useTheme,
} from "react-native-paper";
import { Toast } from "toastify-react-native";
import { usePackage } from "../../src/hooks/usePackages";
import { useStore } from "../../src/store/useStore";

export default function PackageDetailsScreen() {
  const { id } = useLocalSearchParams();
  const theme = useTheme();
  const router = useRouter();
  const bookTrip = useStore((state) => state.bookTrip);
  const user = useStore((state) => state.user);

  // Use the usePackage hook to fetch from Appwrite
  const {
    package: pkg,
    isLoading,
    error,
  } = usePackage(typeof id === "string" ? id : "");

  if (isLoading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  if (error || !pkg) {
    return (
      <View style={styles.center}>
        <Text>Package not found</Text>
      </View>
    );
  }

  const handleBookTrip = () => {
    if (!user) {
      router.push("/(auth)/login");
      return;
    }

    bookTrip({
      packageId: pkg.$id,
      packageTitle: pkg.title,
      destination: pkg.country || pkg.destination,
      departureDate: new Date(),
      returnDate: new Date(
        Date.now() + (parseInt(pkg.duration) || 7) * 86400000
      ),
      travelers: [],
      totalPrice: pkg.price,
    });

    Toast.success("Trip booked successfully!");
    router.replace("/(tabs)/mytrips" as any);
  };

  const generatePDF = async () => {
    try {
      const html = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
              .header { text-align: center; margin-bottom: 30px; }
              .title { font-size: 24px; font-weight: bold; color: #0056D2; margin-bottom: 10px; }
              .price { font-size: 20px; color: #FFC107; font-weight: bold; }
              .image { width: 100%; height: 200px; object-fit: cover; border-radius: 8px; margin-bottom: 20px; }
              .section-title { font-size: 18px; font-weight: bold; margin-top: 20px; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
              .timeline-item { margin-bottom: 15px; }
              .day { font-weight: bold; color: #0056D2; }
              .desc { color: #666; font-size: 14px; margin-top: 5px; }
              .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; }
            </style>
          </head>
          <body>
            <div class="header">
              <div class="title">${pkg.title}</div>
              <div class="price">$${pkg.price}</div>
            </div>
            
            <img src="${pkg.imageUrl}" class="image" />
            
            <div class="section-title">Overview</div>
            <p>${pkg.description}</p>
            
            <div class="section-title">Itinerary</div>
            ${pkg.itinerary
              .map(
                (day) => `
              <div class="timeline-item">
                <div class="day">Day ${day.day}: ${day.title}</div>
                <div class="desc">${day.description}</div>
              </div>
            `
              )
              .join("")}
            
            <div class="footer">
              Generated by Travelling App
            </div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, {
        UTI: ".pdf",
        mimeType: "application/pdf",
      });
    } catch (error) {
      console.error("PDF Generation Error:", error);
      Toast.error("Failed to generate PDF");
    }
  };

  return (
    <View style={{ flex: 1, backgroundColor: theme.colors.background }}>
      <Stack.Screen
        options={{
          headerShown: true,
          headerTransparent: true,
          headerTitle: "",
          headerTintColor: "#fff",
          headerRight: () => (
            <MaterialCommunityIcons
              name="file-download-outline"
              size={24}
              color="#fff"
              style={{ marginRight: 16 }}
              onPress={generatePDF}
            />
          ),
        }}
      />

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Same Hero Container Code... adjusted slightly for header */}
        <View style={styles.heroContainer}>
          <Image
            source={{ uri: pkg.imageUrl }}
            style={styles.heroImage}
            contentFit="cover"
          />
          <LinearGradient
            colors={["rgba(0,0,0,0.3)", "transparent", "rgba(0,0,0,0.8)"]}
            style={styles.heroGradient}
          />

          <View style={styles.titleContainer}>
            <Chip style={styles.regionChip} textStyle={{ color: "#fff" }}>
              {pkg.country}
            </Chip>
            <Text variant="headlineMedium" style={styles.heroTitle}>
              {pkg.title}
            </Text>
          </View>
        </View>

        <View style={styles.contentContainer}>
          {/* Quick Stats */}
          <View style={styles.statsRow}>
            <View style={styles.statItem}>
              <MaterialCommunityIcons
                name="clock-outline"
                size={24}
                color={theme.colors.primary}
              />
              <Text variant="labelMedium">{pkg.duration}</Text>
            </View>
            <View style={styles.statItem}>
              <MaterialCommunityIcons name="star" size={24} color="#FFC107" />
              <Text variant="labelMedium">
                {pkg.rating} ({pkg.reviewCount})
              </Text>
            </View>
            <View style={styles.statItem}>
              <MaterialCommunityIcons
                name="weather-sunny"
                size={24}
                color={theme.colors.secondary}
              />
              <Text variant="labelMedium">Best Time</Text>
            </View>
          </View>

          <Divider style={styles.divider} />

          {/* Description */}
          <Text variant="titleLarge" style={styles.sectionTitle}>
            Overview
          </Text>
          <Text variant="bodyMedium" style={styles.description}>
            {pkg.description}
          </Text>

          {/* Inclusions */}
          <Text variant="titleLarge" style={styles.sectionTitle}>
            What&apos;s Included
          </Text>
          <View style={styles.inclusionsGrid}>
            {pkg.inclusions.map((item, index) => (
              <View key={index} style={styles.inclusionItem}>
                <MaterialCommunityIcons
                  name="check-circle"
                  size={20}
                  color={theme.colors.tertiary}
                />
                <Text variant="bodyMedium" style={styles.inclusionText}>
                  {item}
                </Text>
              </View>
            ))}
          </View>

          {/* Itinerary Timeline */}
          <Text variant="titleLarge" style={styles.sectionTitle}>
            Itinerary
          </Text>
          <View style={styles.timelineContainer}>
            {pkg.itinerary.map((day, index) => (
              <View key={index} style={styles.timelineItem}>
                <View style={styles.timelineLeft}>
                  <Text
                    variant="titleMedium"
                    style={{ color: theme.colors.primary }}
                  >
                    Day {day.day}
                  </Text>
                  <View
                    style={[
                      styles.timelineLine,
                      { backgroundColor: theme.colors.outlineVariant },
                    ]}
                  />
                </View>
                <Surface style={styles.timelineCard} elevation={1}>
                  <Text variant="titleMedium" style={styles.dayTitle}>
                    {day.title}
                  </Text>
                  <Text
                    variant="bodySmall"
                    numberOfLines={3}
                    style={styles.dayDesc}
                  >
                    {day.description}
                  </Text>
                </Surface>
              </View>
            ))}
          </View>

          <View style={styles.bottomSpacer} />
        </View>
      </ScrollView>

      {/* Sticky Bottom Bar */}
      <Surface style={styles.bottomBar} elevation={4}>
        <View>
          <Text variant="labelMedium" style={{ color: theme.colors.outline }}>
            Total Price
          </Text>
          <View style={styles.priceRow}>
            <Text variant="headlineSmall" style={styles.price}>
              ${pkg.price}
            </Text>
            <Text variant="bodySmall"> / person</Text>
          </View>
        </View>
        <Button
          mode="contained"
          onPress={handleBookTrip}
          icon="check-circle"
          style={styles.bookButton}
          contentStyle={{ height: 50 }}
        >
          Plan My Trip
        </Button>
      </Surface>
    </View>
  );
}

const styles = StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingBottom: 20,
  },
  heroContainer: {
    height: 350,
    width: "100%",
    position: "relative",
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  heroGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  titleContainer: {
    position: "absolute",
    bottom: 30,
    left: 20,
    right: 20,
  },
  regionChip: {
    backgroundColor: "rgba(0,0,0,0.6)",
    alignSelf: "flex-start",
    marginBottom: 8,
  },
  heroTitle: {
    color: "#fff",
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  contentContainer: {
    flex: 1,
    marginTop: -20,
    backgroundColor: "#F5F7FA",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  statItem: {
    alignItems: "center",
    gap: 4,
  },
  divider: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontWeight: "bold",
    marginBottom: 12,
    color: "#1A1A2E",
  },
  description: {
    color: "#666",
    marginBottom: 24,
    lineHeight: 22,
  },
  inclusionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  inclusionItem: {
    flexDirection: "row",
    alignItems: "center",
    width: "48%",
    gap: 8,
  },
  inclusionText: {
    fontSize: 13,
  },
  timelineContainer: {
    gap: 16,
  },
  timelineItem: {
    flexDirection: "row",
    gap: 16,
  },
  timelineLeft: {
    alignItems: "center",
    width: 50,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    marginTop: 8,
  },
  timelineCard: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#fff",
    marginBottom: 16,
  },
  dayTitle: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 4,
  },
  dayDesc: {
    color: "#666",
    fontSize: 13,
  },
  bottomSpacer: {
    height: 80,
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    padding: 20,
    paddingBottom: 30, // Safe area
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  price: {
    color: "#0056D2",
    fontWeight: "bold",
  },
  bookButton: {
    borderRadius: 12,
    paddingHorizontal: 8,
  },
});
